# TCL File Generated by Component Editor 18.1
# Tue May 20 15:33:41 BST 2025
# DO NOT MODIFY


# 
# Reconstruction_top "recon_top" v1.0
#  2025.05.20.15:33:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Reconstruction_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME Reconstruction_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME recon_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL reconstruction_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file reconstruction_top.sv SYSTEM_VERILOG PATH reconstruction_top.sv
add_fileset_file anti_difference_rounding.sv SYSTEM_VERILOG PATH anti_difference_rounding.sv
add_fileset_file higher_order_difference.sv SYSTEM_VERILOG PATH higher_order_difference.sv
add_fileset_file modulo_residual.sv SYSTEM_VERILOG PATH modulo_residual.sv
add_fileset_file fixed_to_float.sv SYSTEM_VERILOG PATH fixed_to_float.sv
add_fileset_file floating_to_fixed.sv SYSTEM_VERILOG PATH floating_to_fixed.sv
add_fileset_file mod_divide.v VERILOG PATH mod_divide.v
add_fileset_file anti_diff_div.v VERILOG PATH anti_diff_div.v
add_fileset_file moving_average.sv SYSTEM_VERILOG PATH ip/moving_average.sv
add_fileset_file avg_div.v VERILOG PATH avg_div.v
add_fileset_file adc_to_fixed.sv SYSTEM_VERILOG PATH ip/adc_to_fixed.sv
add_fileset_file fixed_to_dac.sv SYSTEM_VERILOG PATH fixed_to_dac.sv


# 
# parameters
# 
add_parameter WIDTH INTEGER 24 ""
set_parameter_property WIDTH DEFAULT_VALUE 24
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH DESCRIPTION ""
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter pipe_delay INTEGER 10 ""
set_parameter_property pipe_delay DEFAULT_VALUE 10
set_parameter_property pipe_delay DISPLAY_NAME pipe_delay
set_parameter_property pipe_delay WIDTH ""
set_parameter_property pipe_delay TYPE INTEGER
set_parameter_property pipe_delay UNITS None
set_parameter_property pipe_delay ALLOWED_RANGES -2147483648:2147483647
set_parameter_property pipe_delay DESCRIPTION ""
set_parameter_property pipe_delay HDL_PARAMETER true
add_parameter LAMBDA INTEGER 49152 ""
set_parameter_property LAMBDA DEFAULT_VALUE 49152
set_parameter_property LAMBDA DISPLAY_NAME LAMBDA
set_parameter_property LAMBDA WIDTH ""
set_parameter_property LAMBDA TYPE INTEGER
set_parameter_property LAMBDA UNITS None
set_parameter_property LAMBDA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LAMBDA DESCRIPTION ""
set_parameter_property LAMBDA HDL_PARAMETER true
add_parameter FRACTIONAL_BITS INTEGER 16 ""
set_parameter_property FRACTIONAL_BITS DEFAULT_VALUE 16
set_parameter_property FRACTIONAL_BITS DISPLAY_NAME FRACTIONAL_BITS
set_parameter_property FRACTIONAL_BITS WIDTH ""
set_parameter_property FRACTIONAL_BITS TYPE INTEGER
set_parameter_property FRACTIONAL_BITS UNITS None
set_parameter_property FRACTIONAL_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRACTIONAL_BITS DESCRIPTION ""
set_parameter_property FRACTIONAL_BITS HDL_PARAMETER true
add_parameter WINDOW_SIZE INTEGER 100
set_parameter_property WINDOW_SIZE DEFAULT_VALUE 100
set_parameter_property WINDOW_SIZE DISPLAY_NAME WINDOW_SIZE
set_parameter_property WINDOW_SIZE TYPE INTEGER
set_parameter_property WINDOW_SIZE UNITS None
set_parameter_property WINDOW_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WINDOW_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 10
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1
add_interface_port nios_custom_instruction_slave adc_in dataa Input 12
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave valid_out done Output 1
add_interface_port nios_custom_instruction_slave dac_out result Output 8

